version: '3.8'

services:
  express:
    build: .
    env_file:
      - ./.env
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    ports:
      - "${PORT}:${PORT}"

